language: node_js
node_js:
- '0.12'
env:
  global:
  - secure: "1qpa1FnzgTojVnvg8ot9mpc79FuS5fyYFQHXeo3/HCmu1FzDWZtCy01K/0fP5FS+0LET5a7yPeQvDpRWL6qQaGgqbWwGDE2l/mqTvQ7lMdishM443qhpL5RSROkIKHHnDyflxPTdPcAJPnPR9n99X3zis+cYib/wrdPuZAVwnKYfa/aro5YMKd3D61OPPEug/nL9mwMEeEwwTrEBf8PhB9czqUusL+GI9POTAlkz9gb0BhResK9p3u8rPfm3dVwkk7v+tKBlNXc6LZ/ioI+wbaVlqOYGH2sdDCFCEchROm0CrGi+qMCF3PYHfbYfTOVUxnDCCAYvYpcXT6TDk1qwcrwhbu3JQjNC1fQ3ABa26oC9Bvalb7XfHxuqph878N9nu9JfXe/jBLnaEOawuQYhbf009qu5x2H/bLqE/lRXZvfYWmGBDZZ43u3H2CyrfJ+aGZ/6CExqagi7lG4BjnWdydtj0q6r+35ZEdD+DkhZd23vTYpJpM4WDZVTkbpRXCvcj6CbQ4MUkVlxl+//LGQu76oZ5lE/+K+rsBa/9cKEXgKmtDSchDHvqc/y+IOMM6uH7OTlQkPYKJS4mS/IaW41KItlLLd68XrhW9D0GO9ytUM4mqZa2T/gW6XiaPKtR6+2bRTC6jX7XSH2IJgsAMo7xL8Ga0NRtAVf8BdGOF2d/aw="
  - secure: "lhvusnVixn0xx6UviFRnUVS/VoW3E6JUhG+STDU8feFhO+t+QpxlDy+QhWcvcAeL1rumV7EKJJBSAjFA0w08TkbIawTTlK22DVIb+qPBe99mQiLWcbxeLTlsDbn7R6Ehqc0Nv3uFsvik9wci40h2wl2AFATEnabeFribKgadsZfdIiGgNZTeN90C+tSCEUK7k9mFGjmwO3y2IhuNNlH0b7mVLOejogEQEcwzhSu61UqTF0veU118x/rdAG5rpkMSgBnbAilMpZwUazC9goDMBSKpCgLiFIEzgzMXSf7D1VieEQCc5jzPkMzs0qRtsBHjAms4w/GjHmqGAozmW2Q8v/CveHJt/4mYAd3L8iH9uu7QwoW0rE1fimVU+UeycWSieVBKk92xjOt7/CoH9mpuA7FIVnHz8Ycy5UwvDMSgY7rVT1SDCWGchuUIVSX3TAzUjwCay7c/ycG+Dn9UyVzXVXBEu11H90JthOfEuV95Fr1GvLdlIVU6Kq/xiU64/UXU0yPAqYAnSdzTJNCfA1nYJKsbiZF5AGjbnF47gvSkhbSAke7eCMEaBl0Ok+tRFZepuLwY8HMFZ0My+cMYDwIPvog6cFsW01QzR70sn5cy/HrBCN38jXpZh8DJ8tbX4DyexrxeKttAwtVR8u6QgnVGUWlwm7beV5ZORBGc1gep+dU="
branches:
  only:
  - develop
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: contact@makemepulse.com
  api_key:
    secure: RZkB4dH6dOcMn92cqAL65Pqnx+muLV9/ZjhdZFPpdW2jW/Vo2i7g4Nmq5BvclVpEFvORAfApvbAbmNELGtQVQQZTAAjClEKgSlfGULi/qBBX1zxVjOuuq1/nOr05LL9KvUa0IriW5AMUise2NDtP017wLzQTplAOPcCuFeYtHDWhPBfjBgyKEWM1ApuK0mjd9zctqW0RscrZ6DERAYDNNP1ch9hgUeH858xi1PnkbcNjfPClhtnP8T3fKLl7erQQigbMF1OfhOBSvs1uv6kUUMYMtjyMO9aPMAriovw3R2vETuVa3KJ8jSuKEG51QA9dJs6Zy2uzi40TAK9xrU76MiCJdVFSz2r9tfI4lwdxJ093X1XO7KNOzQdUiRwLBztKRWPMWDNvPqhWRDJiQdgusRnznmZjBv2TE2v73bUGQoPVJTMi0qdmdV7iVGMvO1YIUquQGBAhowKDF53uk8ROg/59+Yxpc+wFdwb0SuvjD/746BDT4dKuNKx57PqcBAAF8ij9MlVgztDll/bhLIK+X27q8oTS9wwh6g4ld93wC/kwJGBjTFnQK6X7yE3bp4Z+AOcem1VmAGH5JfdLXuUmlES+fMs676izTlkrcjROTU+DyxnkHje1JPffBSCYSVt6des52ERQvXfGROPJOmExf4SJ1tN0FzsBcRanB1WOak4=
  on:
    branch: master
    repo: plepers/nanogl-vao
